const actionTypes = Object.freeze({
    // app
    APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
    SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
    CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

    // loading
    START_LOADING: "START_LOADING",
    END_LOADING: "END_LOADING",

    // modal
    OPEN_MODAL_LOGIN_SUCCESS: "OPEN_MODAL_LOGIN_SUCCESS",
    OPEN_MODAL_REGISTER_SUCCESS: "OPEN_MODAL_REGISTER_SUCCESS",
    OPEN_MODAL_DELETE_PIN_SUCCESS: "OPEN_MODAL_DELETE_PIN_SUCCESS",

    OPEN_MODAL_EDIT_PIN_SUCCESS: "OPEN_MODAL_EDIT_PIN_SUCCESS",
    OPEN_MODAL_EDIT_PIN_FAILED: "OPEN_MODAL_EDIT_PIN_FAILED",

    // user
    ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
    PROCESS_LOGOUT: "PROCESS_LOGOUT",

    FETCH_USER_BY_ID_SUCCESS: "FETCH_USER_BY_ID_SUCCESS",
    FETCH_USER_BY_ID_FAILED: "FETCH_USER_BY_ID_FAILED",

    FOLLOW_USER_SUCCESS: "FOLLOW_USER_SUCCESS",
    FOLLOW_USER_FAILED: "FOLLOW_USER_FAILED",

    // search
    FETCH_ALL_PIN_BY_SEARCH_SUCCESS: "FETCH_ALL_PIN_BY_SEARCH_SUCCESS",
    FETCH_ALL_PIN_BY_SEARCH_FAILED: "FETCH_ALL_PIN_BY_SEARCH_FAILED",

    // pin
    FETCH_ALL_PIN_SUCCESS: "FETCH_ALL_PIN_SUCCESS",
    FETCH_ALL_PIN_FAILED: "FETCH_ALL_PIN_FAILED",

    FETCH_ALL_PIN_BY_USER_CREATE_SUCCESS:
        "FETCH_ALL_PIN_BY_USER_CREATE_SUCCESS",
    FETCH_ALL_PIN_BY_USER_CREATE_FAILED: "FETCH_ALL_PIN_BY_USER_CREATE_FAILED",

    FETCH_ALL_PIN_BY_USER_SAVE_SUCCESS: "FETCH_ALL_PIN_BY_USER_SAVE_SUCCESS",
    FETCH_ALL_PIN_BY_USER_SAVE_FAILED: "FETCH_ALL_PIN_BY_USER_SAVE_FAILED",

    FETCH_PIN_BY_ID_SUCCESS: "FETCH_PIN_BY_ID_SUCCESS",
    FETCH_PIN_BY_ID_FAILED: "FETCH_PIN_BY_ID_FAILED",

    CREATE_NEW_PIN_SUCCESS: "CREATE_NEW_PIN_SUCCESS",
    CREATE_NEW_PIN_FAILED: "CREATE_NEW_PIN_FAILED",

    UPDATE_PIN_SUCCESS: "UPDATE_PIN_SUCCESS",
    UPDATE_PIN_FAILED: "UPDATE_PIN_FAILED",

    DELETE_PIN_SUCCESS: "DELETE_PIN_SUCCESS",
    DELETE_PIN_FAILED: "DELETE_PIN_FAILED",

    SAVE_PIN_SUCCESS: "SAVE_PIN_SUCCESS",
    SAVE_PIN_FAILED: "SAVE_PIN_FAILED",

    // comment pin
    FETCH_COMMENT_PIN_SUCCESS: "FETCH_COMMENT_PIN_SUCCESS",
    FETCH_COMMENT_PIN_FAILED: "FETCH_COMMENT_PIN_FAILED",

    COMMENT_PIN_SUCCESS: "COMMENT_PIN_SUCCESS",
    COMMENT_PIN_FAILED: "COMMENT_PIN_FAILED",

    LIKE_COMMENT_SUCCESS: "LIKE_COMMENT_SUCCESS",
    LIKE_COMMENT_FAILED: "LIKE_COMMENT_FAILED",

    DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
    DELETE_COMMENT_FAILED: "DELETE_COMMENT_FAILED",
});

export default actionTypes;
